// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KLExtensions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "64f8ed13-2bdc-449c-aa3d-9a8a69a14e93";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidPackageCmdSetString = "e2927997-aef0-4d0f-9392-a44d51a7b2c2";
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);

        public const string guidPackageSurroundWithCmdSetString = "060f8145-dd46-4faa-ab59-dfdbeea72dcc";
        public static Guid guidPackageSurroundWithCmdSet = new Guid(guidPackageSurroundWithCmdSetString);

        public const string guidImagesString = "d8bf0f90-62ba-4911-b5a7-3cac6baa0d50";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int KLExtensionsMenuGroup = 0x1020;
        public const int KLExtensionsMenu = 0x1021;
        public const int RemoveCommentCommandId = 0x0100;
        public const int RemoveRegionsCommandId = 0x0200;
        public const int SurroundWithMenuGroup = 0x1020;
        public const int SurroundWithCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPic3 = 0x0003;
        public const int bmpPic4 = 0x0004;
        public const int bmpPic5 = 0x0005;
        public const int bmpPic6 = 0x0006;
    }
}